/**
 * Build script for perimetre/tokens.
 *
 * Reads W3C DTCG JSON token sets and generates CSS files using
 * Style Dictionary + tokens-studio/sd-transforms.
 *
 * Output: dist/brands/brand.css files with `@layer pui.primitive` and `@layer pui.semantic`.
 *
 * Usage: tsx src/scripts/build.ts
 */

import { register } from '@tokens-studio/sd-transforms';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import type { TransformedToken } from 'style-dictionary/types';

const currentDir = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(currentDir, '../..');

const BRANDS = ['acorn', 'sprig', 'stelpro', 'cima'] as const;

// Register Tokens Studio transforms into Style Dictionary
void register(StyleDictionary);

/**
 * Formats a single token as a CSS custom property declaration.
 *
 * Preserves DTCG references by converting `{path.to.token}` to `var(--path-to-token)`.
 */
function formatToken(token: TransformedToken): string {
  const name = `--${token.name}`;
  const origValue = String(token.original.$value ?? token.original.value ?? '');

  let value: string;

  if (origValue.includes('{')) {
    // Has DTCG references — convert {path.to.token} to var(--path-to-token)
    value = origValue.replace(/\{([^}]+)\}/g, (_, refPath: string) => {
      return `var(--${refPath.replace(/\./g, '-')})`;
    });
  } else {
    // Raw value — use the SD-transformed value
    value = String(token.$value ?? token.value ?? '');
  }

  return `    ${name}: ${value};`;
}

/**
 * Checks if a token belongs to the primitive layer.
 */
function isPrimitive(token: { path: string[] }): boolean {
  return token.path[1] === 'primitive';
}

/**
 * Custom format: outputs CSS variables wrapped in `@layer` with brand selector.
 *
 * Splits tokens into primitive (`pui.primitive`) and semantic (everything else)
 * layers, preserving DTCG references as CSS `var()` references.
 */
StyleDictionary.registerFormat({
  name: 'css/pui-brand',
  /** Generates layered CSS output for a brand. */
  format: ({ dictionary, options }) => {
    const brand = options.brand as string;
    const selector =
      brand === 'acorn' ? '[data-pui-brand]' : `[data-pui-brand='${brand}']`;

    const primitiveTokens = dictionary.allTokens.filter(isPrimitive);
    const semanticTokens = dictionary.allTokens.filter((t) => !isPrimitive(t));

    const sections: string[] = [];

    if (primitiveTokens.length > 0) {
      const vars = primitiveTokens.map(formatToken).join('\n');
      sections.push(`@layer pui.primitive {\n  ${selector} {\n${vars}\n  }\n}`);
    }

    if (semanticTokens.length > 0) {
      const vars = semanticTokens.map(formatToken).join('\n');
      sections.push(`@layer pui.semantic {\n  ${selector} {\n${vars}\n  }\n}`);
    }

    const header = `/* Auto-generated by @perimetre/tokens build script. Do not edit manually. */`;
    return header + '\n' + sections.join('\n\n') + '\n';
  }
});

/**
 * Builds CSS brand files from JSON token sets.
 *
 * For acorn: outputs all primitives + semantics.
 * For brands: outputs only the brand override tokens.
 * All token sets are loaded as source so references resolve correctly.
 */
async function build(): Promise<void> {
  for (const brand of BRANDS) {
    const isBase = brand === 'acorn';

    const baseSets = [
      resolve(ROOT, 'src/sets/primitives/**/*.json'),
      resolve(ROOT, 'src/sets/semantic/base.json')
    ];

    const source = isBase
      ? baseSets
      : [...baseSets, resolve(ROOT, `src/sets/brands/${brand}.json`)];

    const sd = new StyleDictionary({
      source,
      log: {
        // Brand tokens intentionally override base tokens — suppress collision warnings
        verbosity: 'silent'
      },
      preprocessors: ['tokens-studio'],
      platforms: {
        css: {
          // Only use name transform — values are already in correct CSS format
          transforms: ['name/kebab'],
          buildPath: `${ROOT}/dist/brands/`,
          files: [
            {
              destination: `${brand}.css`,
              format: 'css/pui-brand',
              options: {
                brand
              },
              // For brands: only output tokens from the brand file
              // For acorn: output everything
              filter: isBase
                ? undefined
                : (token: TransformedToken) =>
                    token.filePath.includes(`brands/${brand}`)
            }
          ]
        }
      }
    });

    await sd.buildAllPlatforms();
    console.log(`Built dist/brands/${brand}.css`);
  }

  console.log('Done!');
}

void build().catch((err: unknown) => {
  console.error('Build failed:', err);
  process.exit(1);
});
